// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufKQaHlcy14BENKfJmjFlYo3be-fydrI',
    appId: '1:232649496267:web:289ff732413de7d034ad4e',
    messagingSenderId: '232649496267',
    projectId: 'weather-app-d0a2f',
    authDomain: 'weather-app-d0a2f.firebaseapp.com',
    databaseURL: 'https://weather-app-d0a2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-d0a2f.appspot.com',
    measurementId: 'G-Z6KLYE83HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYu7KPvCzzfBVKE5I1kUwaiEa8P5pbutQ',
    appId: '1:232649496267:android:1f5e467c553901d634ad4e',
    messagingSenderId: '232649496267',
    projectId: 'weather-app-d0a2f',
    databaseURL: 'https://weather-app-d0a2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-d0a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopihJ_wMGn6w8z6rpcTPb0BWZarIAXvs',
    appId: '1:232649496267:ios:3dbd3754bba96c9434ad4e',
    messagingSenderId: '232649496267',
    projectId: 'weather-app-d0a2f',
    databaseURL: 'https://weather-app-d0a2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-d0a2f.appspot.com',
    androidClientId: '232649496267-b5n521n7geq3rmdceu2t52ocb7sv0o9n.apps.googleusercontent.com',
    iosClientId: '232649496267-htk6nk2hppn0tni39j1k85igvdushant.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopihJ_wMGn6w8z6rpcTPb0BWZarIAXvs',
    appId: '1:232649496267:ios:3dbd3754bba96c9434ad4e',
    messagingSenderId: '232649496267',
    projectId: 'weather-app-d0a2f',
    databaseURL: 'https://weather-app-d0a2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-d0a2f.appspot.com',
    androidClientId: '232649496267-b5n521n7geq3rmdceu2t52ocb7sv0o9n.apps.googleusercontent.com',
    iosClientId: '232649496267-htk6nk2hppn0tni39j1k85igvdushant.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
